### ISSUE TITLE
Get rid of Thor Loser on the splash screen (Agree on a name for the app)

### ISSUE THREAD

**Issue by jt4uc** [nicklytle/GDRGEnergyGame#1]

**Comment by dylanhellems** [comment]
+1

**Comment by jt4uc** [comment]
Suggestions:
Hestia - origin: Greek goddess of the hearth
Helios - origin: Greek personification of the sun
Eta - origin: Greek symbol that denotes energy conversion efficiency

**Comment by davidamin** [comment]
Closing for lack of sanity

**Comment by dylanhellems** [comment]
Going with EnergyQuest for now
