### ISSUE TITLE
What is the gem thing? (Updated issue: Replace joules with icon)

### ISSUE THREAD

**Issue by jt4uc** [nicklytle/GDRGEnergyGame#17]
I think it has something to do with the joules, but it's floating too far away from the joules

**Comment by nicklytle** [comment]
What screen is this?

**Comment by jt4uc** [comment]
On the profile screen. Apparently it indicates the joules, but we should really rename joules to "jewels". Some people will get the joke without misleading people who actually know what "joules" is

**Comment by dylanhellems** [comment]
Will replace "joules" and it's abbreviation on the quest list, quest form, and user form with an icon once we have one

**Comment by dylanhellems** [comment]
Replaced by new issue
