### ISSUE TITLE
Drapes of Wrath confusion

### ISSUE THREAD

**Issue by jt4uc** [nicklytle/GDRGEnergyGame#20]
If drapes are good, why are they wrathful? Also, why do they save energy? I'm an incompetent user - I can’t google

**Comment by nicklytle** [comment]
The puns stay. They will always stay. >:(

**Comment by nicklytle** [comment]
In all seriousness, she suggested that it was okay to have punny names (she really likes puns). We can try a different pun for the final one though if one is better.
