### ISSUE TITLE
Dialog text only appears when you tap and hold 

### ISSUE THREAD

**Issue by jt4uc** [nicklytle/GDRGEnergyGame#32]

**Comment by dylanhellems** [comment]
Could you clarify on this one what you mean?

**Comment by jt4uc** [comment]
You can see the "OK" to exit from the dialog, but not the text of the dialog itself. See screenshot. 
![screen shot 2016-02-23 at 6 16 42 pm](https://cloud.githubusercontent.com/assets/5541031/13270111/d94cec22-da59-11e5-8378-06145cf5973b.png) Interestingly enough when I was making this screenshot, I discovered the text is in black on a transparent background, which is why you can't see it

**Comment by dylanhellems** [comment]
Yah, we need to deal with the theme. This is an extension of #2 probably.
