### ISSUE TITLE
Registration - drop down menu for states looked out of whack

### ISSUE THREAD

**Issue by jt4uc** [nicklytle/GDRGEnergyGame#4]
Maybe it's just the device simulator?

**Comment by jt4uc** [comment]
here's a screenshot, because peeps had questions
![screen shot 2016-02-25 at 6 54 59 pm](https://cloud.githubusercontent.com/assets/5541031/13338774/af206688-dbf1-11e5-93c6-2980f1350a75.png)

**Comment by dylanhellems** [comment]
Looks better in current theme on my computer
