### ISSUE TITLE
"Which bulb is the most energy efficient?"

### ISSUE THREAD

**Issue by jt4uc** [nicklytle/GDRGEnergyGame#48]
This question is misleading, because it implies which of the following when first reading the question and "none of the above" just work nicely with "which of the following"
Also, Aren't LEDs and CFLs tied?
Also, we need to eventually remove Bulbasaur as the correct answer, so this issue will remind us of that
Also that quiz is just BS, so this issue will remind us of that

**Comment by dylanhellems** [comment]
Database dropped, new quests going in
